dt.Rows.Count :23  ErrorDate-10/27/2017 1:00:39 PM
dtNew.Rows.Count :22  ErrorDate-10/27/2017 1:00:39 PM
dtNew.Rows.Count :1  ErrorDate-10/27/2017 1:00:39 PM
dt.Rows.Count :23  ErrorDate-10/27/2017 1:03:22 PM
dtNew.Rows.Count :22  ErrorDate-10/27/2017 1:03:22 PM
dtNew.Rows.Count :1  ErrorDate-10/27/2017 1:03:22 PM
something happened  ErrorDate-10/27/2017 1:17:05 PM
An item with the same key has already been added.   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GloommeApi.Controllers.MessageController.GetMessageProvider(Int32 ProviderID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Controllers\MessageController.cs:line 150  ErrorDate-10/27/2017 1:57:44 PM
An error occurred while preparing the command definition. See the inner exception for details. :    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 170  ErrorDate-10/28/2017 1:03:29 AM
The best overloaded method match for 'System.Collections.Generic.List<System.Dynamic.ExpandoObject>.Add(System.Dynamic.ExpandoObject)' has some invalid arguments :    at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 192  ErrorDate-10/28/2017 1:26:31 AM
The best overloaded method match for 'System.Collections.Generic.List<System.Dynamic.ExpandoObject>.Add(System.Dynamic.ExpandoObject)' has some invalid arguments :    at CallSite.Target(Closure , CallSite , Object , <>f__AnonymousType6`3 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 190  ErrorDate-10/28/2017 1:29:20 AM
'<>f__AnonymousType5<int?,string>' does not contain a definition for 'Jobs' :    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 190  ErrorDate-10/28/2017 1:32:35 AM
'<>f__AnonymousType5<int?,string>' does not contain a definition for 'Jobs' :    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 190  ErrorDate-10/28/2017 11:00:58 AM
The best overloaded method match for 'System.Collections.Generic.List<System.Dynamic.ExpandoObject>.Add(System.Dynamic.ExpandoObject)' has some invalid arguments :    at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at GloommeApi.Codes.DAL_SN_Messages.FetchCustomerMessages(Int32 CustomerID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Codes\DAL_SN_Messages.cs:line 194  ErrorDate-10/28/2017 12:11:21 PM
23  ErrorDate-10/28/2017 12:23:42 PM
1  ErrorDate-10/28/2017 12:33:39 PM
1  ErrorDate-10/28/2017 12:35:38 PM
1  ErrorDate-10/28/2017 12:39:25 PM
1  ErrorDate-10/28/2017 12:40:52 PM
1  ErrorDate-10/28/2017 12:40:56 PM
1  ErrorDate-10/28/2017 12:48:33 PM
1  ErrorDate-10/28/2017 12:49:10 PM
1  ErrorDate-10/28/2017 12:49:13 PM
1  ErrorDate-10/28/2017 12:50:05 PM
1  ErrorDate-10/28/2017 12:50:59 PM
1  ErrorDate-10/28/2017 12:51:04 PM
1  ErrorDate-10/28/2017 12:52:01 PM
1  ErrorDate-10/28/2017 12:54:10 PM
1  ErrorDate-10/28/2017 12:54:41 PM
1  ErrorDate-10/28/2017 12:54:57 PM
1  ErrorDate-10/28/2017 12:55:52 PM
1  ErrorDate-10/28/2017 12:55:54 PM
1  ErrorDate-10/28/2017 12:58:50 PM
1  ErrorDate-10/28/2017 12:59:34 PM
1  ErrorDate-10/28/2017 1:02:12 PM
1  ErrorDate-10/29/2017 4:40:19 AM
1  ErrorDate-10/29/2017 4:58:25 AM
1  ErrorDate-10/29/2017 4:58:26 AM
1  ErrorDate-10/29/2017 5:00:50 AM
1  ErrorDate-10/29/2017 5:01:11 AM
1  ErrorDate-10/29/2017 5:01:51 AM
1  ErrorDate-10/29/2017 5:01:57 AM
1  ErrorDate-10/29/2017 5:02:47 AM
1  ErrorDate-10/29/2017 5:04:21 AM
1  ErrorDate-10/29/2017 5:04:25 AM
1  ErrorDate-10/29/2017 5:04:28 AM
1  ErrorDate-10/29/2017 5:04:28 AM
1  ErrorDate-10/29/2017 5:05:59 AM
1  ErrorDate-10/29/2017 5:14:09 AM
1  ErrorDate-10/29/2017 5:14:14 AM
1  ErrorDate-10/29/2017 5:15:26 AM
1  ErrorDate-10/29/2017 5:15:30 AM
1  ErrorDate-10/29/2017 5:15:38 AM
1  ErrorDate-10/29/2017 5:15:48 AM
1  ErrorDate-10/29/2017 5:15:54 AM
1  ErrorDate-10/29/2017 5:22:17 AM
1  ErrorDate-10/29/2017 5:30:18 AM
1  ErrorDate-10/29/2017 5:47:07 AM
1  ErrorDate-10/29/2017 5:47:31 AM
1  ErrorDate-10/29/2017 9:28:02 AM
Column 'PostMessage' does not belong to table Table.   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at GloommeApi.Controllers.MessageController.GetMessageProvider(Int32 ProviderID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Controllers\MessageController.cs:line 145  ErrorDate-10/29/2017 9:28:31 AM
Column 'PostMessage' does not belong to table Table.   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at GloommeApi.Controllers.MessageController.GetMessageProvider(Int32 ProviderID) in C:\inetpub\wwwroot\GloommeApi\GloommeApi\Controllers\MessageController.cs:line 145  ErrorDate-10/29/2017 9:28:45 AM
